import type { Config } from 'tailwindcss';

const v = (name: string) => `rgb(var(--${name}) / <alpha-value>)`;

export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        bg: v('bg'),
        surface: v('surface'),
        surface2: v('surface2'),
        sunken: v('sunken'),
        line: v('line'),
        line2: v('line2'),
        ink: v('ink'),
        ink2: v('ink2'),
        ink3: v('ink3'),
        accent: { DEFAULT: v('accent'), ink: v('accent-ink'), soft: v('accent-soft'), line: v('accent-line') },
        'on-accent': v('on-accent'),
        ok: { DEFAULT: v('ok'), soft: v('ok-soft'), line: v('ok-line') },
        'on-ok': v('on-ok'),
        bad: { DEFAULT: v('bad'), soft: v('bad-soft'), line: v('bad-line') },
        'on-bad': v('on-bad'),
        warn: { DEFAULT: v('warn'), soft: v('warn-soft'), line: v('warn-line') },
        code: { DEFAULT: v('code'), ink: v('code-ink'), dim: v('code-dim'), add: v('code-add'), del: v('code-del'), line: v('code-line') },
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        mono: ['var(--font-geist-mono)', 'ui-monospace', 'SFMono-Regular', 'Menlo', 'monospace'],
      },
      boxShadow: {
        card: '0 1px 0 rgb(255 255 255 / 0.02) inset, 0 1px 2px rgb(var(--shadow) / 0.3)',
        pop: '0 24px 60px -24px rgb(var(--shadow) / 0.75), 0 0 0 1px rgb(255 255 255 / 0.02) inset',
        ring: '0 0 0 3px rgb(var(--accent) / 0.22)',
        glow: '0 0 0 1px rgb(var(--accent) / 0.4), 0 10px 30px -12px rgb(var(--accent) / 0.55)',
      },
      transitionTimingFunction: {
        out: 'cubic-bezier(0.23, 1, 0.32, 1)',
        'in-out': 'cubic-bezier(0.77, 0, 0.175, 1)',
        drawer: 'cubic-bezier(0.32, 0.72, 0, 1)',
      },
      keyframes: {
        'fade-in': { from: { opacity: '0' }, to: { opacity: '1' } },
        'slide-up': { from: { opacity: '0', transform: 'translateY(6px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        'slide-left': { from: { opacity: '0', transform: 'translateX(24px)' }, to: { opacity: '1', transform: 'translateX(0)' } },
        'screen-in': { from: { opacity: '0', transform: 'translateY(8px)', filter: 'blur(3px)' }, to: { opacity: '1', transform: 'none', filter: 'none' } },
        'pop-in': { from: { opacity: '0', transform: 'scale(0.96) translateY(-4px)' }, to: { opacity: '1', transform: 'none' } },
        'msg-in': { from: { opacity: '0', transform: 'translateY(6px)', filter: 'blur(3px)' }, to: { opacity: '1', transform: 'none', filter: 'none' } },
        'toast-in': { from: { opacity: '0', transform: 'translateY(10px)', filter: 'blur(4px)' }, to: { opacity: '1', transform: 'none', filter: 'none' } },
        stamp: { from: { opacity: '0', transform: 'rotate(-4deg) scale(1.25)' }, to: { opacity: '1', transform: 'rotate(-4deg) scale(1)' } },
        pulse2: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.45' } },
        caret: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0' } },
        blink: { '0%,80%,100%': { opacity: '0.25' }, '40%': { opacity: '1' } },
        tour: { '0%,100%': { boxShadow: '0 0 0 3px rgb(var(--accent) / 0.35)' }, '50%': { boxShadow: '0 0 0 9px rgb(var(--accent) / 0.06)' } },
        ping2: { '0%': { boxShadow: '0 0 0 0 rgb(var(--ok) / 0.5)' }, '70%': { boxShadow: '0 0 0 7px rgb(var(--ok) / 0)' }, '100%': { boxShadow: '0 0 0 0 rgb(var(--ok) / 0)' } },
      },
      animation: {
        'fade-in': 'fade-in 160ms cubic-bezier(0.23, 1, 0.32, 1)',
        'slide-up': 'slide-up 220ms cubic-bezier(0.23, 1, 0.32, 1)',
        'slide-left': 'slide-left 260ms cubic-bezier(0.32, 0.72, 0, 1)',
        'screen-in': 'screen-in 260ms cubic-bezier(0.23, 1, 0.32, 1) both',
        'pop-in': 'pop-in 150ms cubic-bezier(0.23, 1, 0.32, 1) both',
        'msg-in': 'msg-in 260ms cubic-bezier(0.23, 1, 0.32, 1) both',
        'toast-in': 'toast-in 260ms cubic-bezier(0.23, 1, 0.32, 1) both',
        stamp: 'stamp 360ms cubic-bezier(0.23, 1, 0.32, 1) both',
        pulse2: 'pulse2 1.4s ease-in-out infinite',
        caret: 'caret 1s step-end infinite',
        blink: 'blink 1s infinite',
        tour: 'tour 1.6s ease-in-out infinite',
        ping2: 'ping2 2s ease-out infinite',
      },
    },
  },
  plugins: [],
} satisfies Config;
